alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias shelli="ssh -p 443 gustafla.space"
alias tmc="java -cp ~/.local/share/tmc-cli fi.helsinki.cs.tmc.cli.Application"
alias acp="git add -A && git commit && git push"
alias make="make -j $(nproc)"
alias jacoco="mvn test jacoco:report && xdg-open target/site/jacoco/index.html"
alias checkstyle="mvn jxr:jxr checkstyle:checkstyle && xdg-open target/site/checkstyle.html"
