alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias shelli="ssh -p 443 gustafla.space"
alias tmc="java -cp ~/.local/share/tmc-cli fi.helsinki.cs.tmc.cli.Application"
alias acp="git add -A && git commit && git push"
alias make="make -j $(nproc)"
alias lynx="lynx -cfg=${HOME}/.config/lynx/lynx.cfg"
