[misc]
disable = [
  "cargo",
  "containers",
  "gnome_shell_extensions",
  "helix",
  "lensfun",
  "node",
  "pip3",
  "stack",
  "vim",
]
no_self_update = true

# Additional git repositories to pull
[git]
repos = ["~/.pass/", "~/misc/gitolite-admin/"]
