disable = ["cargo", "pip3", "gnome_shell_extensions", "containers"]
display_preamble = false

# Additional git repositories to pull
[git]
repos = ["~/.pass/", "~/misc/gitolite-admin/"]

[commands]
"Helix chmod fix" = "sudo chmod a+r /var/lib/helix/runtime/grammars/*"
