disable = ["cargo", "pip3", "gnome_shell_extensions"]

# Additional git repositories to pull
[git]
repos = [
    "~/.password-store/",
    "~/misc/gitolite-admin/"
]

[commands]
"Podman Prune" = "podman container prune -f && podman image prune -f"