disable = ["cargo", "pip3", "gnome_shell_extensions"]

# Additional git repositories to pull
[git]
repos = [
    "~/code/*/",
    "~/.password-store/",
    "~/misc/gitolite-admin/"
]

[commands]
"Vdirsyncer" = "which vdirsyncer 2>/dev/null && vdirsyncer sync || echo Not installed"
