theme = "catppuccin_mocha"

[editor]
mouse = false
idle-timeout = 100
cursor-shape.normal = "block"
cursor-shape.insert = "bar"
cursor-shape.select = "underline"
cursorline = true
auto-save = true
color-modes = true
rulers = [80, 120]
bufferline = "multiple"
soft-wrap.enable = true
lsp.display-inlay-hints = false
lsp.display-messages = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = [
  "file-name",
  "file-modification-indicator",
  "spacer",
  "version-control",
]
right = ["position", "selections", "primary-selection-length"]
