theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
idle-timeout = 100
cursorline = true
auto-save = true
color-modes = true
rulers = [80, 120]
bufferline = "multiple"
soft-wrap.enable = true
end-of-line-diagnostics = "hint"

[editor.lsp]
display-inlay-hints = false
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = [
  "file-name",
  "file-modification-indicator",
  "spacer",
  "version-control",
]
right = ["position", "selections", "primary-selection-length"]

[keys.normal]
space = { H = ":edit ~/.config/helix/cheatsheet.md" }
