theme = "dark_high_contrast"

[editor]
mouse = false
idle-timeout = 100
cursor-shape.normal = "block"
cursor-shape.insert = "bar"
cursor-shape.select = "underline"
cursorline = true
auto-save = true
color-modes = true
rulers = [80, 120]
bufferline = "multiple"
