[language-server.glsl_analyzer]
command = "glsl_analyzer"

[language-server.wgsl-analyzer]
command = "wgsl-analyzer"

[language-server.texlab]
config.texlab.build.onSave = true
config.texlab.build.args = ["-pdf", "%f"]

[language-server.tinymist]
config.exportPdf = "onSave"
config.preview.background.enabled = true
config.preview.background.args = [
  "--data-plane-host=127.0.0.1:23635",
  "--invert-colors=never",
]

[language-server.ltex-ls-plus]
command = "ltex-ls-plus"

[language-server.typst-languagetool]
command = "typst-languagetool-lsp"
config = { backend = "bundle", dictionary.en-GB = [
    "Heljanko",
    "VideoCore",
], languages = { en = "en-GB" }}

[language-server.rust-analyzer]
config.rust-analyzer.check.command = "clippy"
config.rust-analyzer.cargo.allFeatures = true

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "latex"
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = "latexindent", args = ["-y", "defaultIndent:'  '"] }
language-servers = ["texlab", "ltex-ls-plus"]

[[language]]
name = "typst"
auto-format = true
language-servers = ["tinymist", "typst-languagetool"]

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "jsx"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "tsx"
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "glsl"
auto-format = true
language-servers = ["glsl_analyzer"]

[[language]]
name = "wgsl"
auto-format = true
language-servers = ["wgsl-analyzer"]

[[language]]
name = "text"
scope = "text.txt"
file-types = ["txt"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "haskell"
auto-format = true
