[language-server.texlab]
config.texlab.rootDirectory = "."
config.texlab.build.onSave = true
config.texlab.build.args = ["-pdf", "%f"]
config.texlab.chktex.onEdit = true

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "latex"
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = "latexindent", args = ["-y", "defaultIndent:'  '"] }

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "jsx"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "tsx"
auto-format = true

[[language]]
name = "toml"
auto-format = true
